### ISSUE TITLE
install hangs

### ISSUE THREAD

**Issue by Hoiitsme** [Aterfax/DCS-World-Dedicated-Server-Docker#38]
from logs:
0058:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0058:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."

then halts after:
0110:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0110:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0110:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0114:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 00007FFFFF42FF50
0110:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
0110:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
0110:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.12
0110:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.12
0110:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
0110:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
0110:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.12
0110:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.12
0110:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
0110:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.4
0110:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.12
0110:fixme:cryptasn:CryptDecodeObjectEx Unsupported decoder for lpszStructType 1.3.6.1.4.1.311.2.1.12
0110:fixme:file:NtLockFile I/O completion on lock not implemented yet

**Comment by Aterfax** [comment]
Those log messages are spurious. Cannot replicate the issue, please provide further info on how you are invoking the docker image, the specific docker image version and details of the host machine running the docker.

**Comment by Aterfax** [comment]
Can't fix what I cannot see. Please re-open with further details if you can provide them and I will investigate further.

**Comment by EricCaverly** [comment]
I cannot speak for [Hoiitsme](https://github.com/Hoiitsme) but I experienced this issue after a failed install attempt due to no Firewall policy allowing container -> internet traffic, and/or mounting `/app/` as a volume when it should not have been. This was done because I was not sure at first where DCS was installed and I am running this in swarm so it must be persistent. 

My hosting environment: 
Ubuntu 24.04 LTS
Docker 26.1.3
Docker compose 2.27.0
Running in docker swarm with container on mac-vlan network
Almost default .env file

It seems fixing the firewall policy, stopping the dcs stack, running `rm -rf config` on the docker host, and re-deploying the stack was enough to fix the issue.
