### ISSUE TITLE
DCSServerbot broken after self-update - missing module sqlparse

### ISSUE THREAD

**Issue by CC1337** [Aterfax/DCS-World-Dedicated-Server-Docker#91]
Hi,

after a restart of my container the DCSServerBot does a self-update, which breaks the installation and it won't start again. Also after the update, the installation script will fail with the same error.
I reproduced it with backups of my VM/container.
The issue should be exactly this commit in this file: https://github.com/Special-K-s-Flightsim-Bots/DCSServerBot/commit/1f9473058196616caa228e50686c119214f3cfda

```
Traceback (most recent call last):
  File "C:\users\abc\DCSServerBot\install.py", line 15, in <module>
    from core import utils, SAVED_GAMES, translations, COMMAND_LINE_ARGS
  File "C:\users\abc\DCSServerBot\core\__init__.py", line 13, in <module>
    from .data.impl.nodeimpl import *
  File "C:\users\abc\DCSServerBot\core\data\impl\nodeimpl.py", line 14, in <modu
le>
    import sqlparse
ModuleNotFoundError: No module named 'sqlparse'
0120:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 00007FFFFE1FE3E0
Please press any key to continue...
```

I think the python environment in the container needs to be extended and this module added. I will take a look if I can find out how, but I'd like to make you aware already.

**Comment by CC1337** [comment]
Yes it did. I found a check in the python VENV exists in e.g. the install script, and if it does, the requirements are not reinstalled.
A clean setup likely would have worked.
I fixed it now inside my container by running this in the DCSServerbot dir:
```
SET VENV=%USERPROFILE%\.dcssb
python -m pip install --upgrade pip
python -m venv "%VENV%"
"%VENV%\Scripts\python.exe" -m pip install -r requirements.txt
```
I took it from here: https://github.com/Special-K-s-Flightsim-Bots/DCSServerBot/blob/master/install.cmd#L17

Do you think the issue might be on DCSServerbot side breaking the update path? Or on mine, somehow :D

**Comment by Aterfax** [comment]
I was expecting the `run.cmd` to eventually iterate through to `update.py` as here:

 https://github.com/Special-K-s-Flightsim-Bots/DCSServerBot/blob/487ec1ccca6b742db3d055a3d533536d68613a5f/run.cmd#L37-L51
 
This should then subsequently run https://github.com/Special-K-s-Flightsim-Bots/DCSServerBot/blob/487ec1ccca6b742db3d055a3d533536d68613a5f/update.py#L37-L40

But I expect this is not occuring because the container's auto updater does the Git pull update so this logic is never triggered because modules is never set true here: https://github.com/Special-K-s-Flightsim-Bots/DCSServerBot/blob/487ec1ccca6b742db3d055a3d533536d68613a5f/update.py#L31-L33

So ultimately it looks like will need to amend the container's update script to take care of the Python environment update also.
